server:
  port: 8762

spring:
  application:
    name: cloud-order
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/milo_order?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true
    username: root
    password: 123456hao123
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
      idle-timeout: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      max-lifetime: 1800000

#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#熔断配置（配置微服务之间的调用超时）
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 200 #参考：https://blog.csdn.net/banqgg/article/details/88536483
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
  threadpool: #hystrix线程池配置 参考：https://www.cnblogs.com/seifon/p/9921774.html
    default:
      coreSize: 10 #并发执行的最大线程数，默认10
      maxQueueSize: 500 #BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5

#mybatis-plus
mybatis-plus:
  type-aliases-package: com.luke.cloud.order.bean
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: uuid
  configuration:
    map-underscore-to-camel-case: true

#milo tcc 配置
milo-tcc:
  model-name: order
  retry-max: 3
  milo-db-config:
    url: jdbc:mysql://127.0.0.1:3306/milo_tcc?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true
    username: root
    password: 123456hao123
    minimum-idle: 20
    maximum-pool-size: 100
    idle-timeout: 30000
    connection-timeout: 30000
    connection-test-query: SELECT 1
    max-lifetime: 1800000
